name: Basic CI

on:
  push:
    branches: [ main ]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up python 
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Docker setup
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Run tests script 
      - name: run tests
        run: |
          pytest test.py

      # Build and deploy script
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-flask-app:${{ github.sha }} .   
      
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/simple-flask-app:${{ github.sha }}

      - name: edit k8s deployment file
        run: |
          sed -i "s|harshapillari03/simple-flask-app:latest|${{ secrets.DOCKER_USERNAME }}/simple-flask-app:${{ github.sha }}|g" deploy/flask-deployment.yml

      - name: Commit updated manifest file
        run: |
          git config --global user.name "Harshavardhan0007"
          git config --global user.email "pillariharshavardhan.16@gmail.com"
          git add deploy/flask-deployment.yml
          git commit -m "Update image to ${{ github.sha}}" || exit 0
          git push
          
      

